### ISSUE TITLE
Client side rendering

### ISSUE THREAD

**Issue by capriosa** [GraphCMS/example_01_nextjs_apollo#3]
Does this example use client side rendering or only SSR?

**Comment by mlukaszczyk** [comment]
Hey @capriosa, sorry for the late response! The code was a little buggy since we haven't really digged deep into Nextjs, so it was SSR only. A fellow community member @hmeissner fixed this in a PR and it took us a while to merge this (shame on us 🙏). It's now supposed to SSR on first load and then switch to client side rendeing. Please let me know if you need any further help and feel free to join our slack at slack.graphcms.com!
